language: csharp
solution: JT1078.sln
dotnet: 3.0.100
os: linux
mono: none
dist: trusty2
script:
 - dotnet restore src/JT1078.sln
 - dotnet build src/JT1078.Protocol.Test/JT1078.Protocol.Test.csproj
 - dotnet test src/JT1078.Protocol.Test/JT1078.Protocol.Test.csproj
 - dotnet build src/JT808.Protocol.Extensions.JT1078.Test/JT808.Protocol.Extensions.JT1078.Test.csproj
 - dotnet test src/JT808.Protocol.Extensions.JT1078.Test/JT808.Protocol.Extensions.JT1078.Test.csproj
 - dotnet build src/JT809.Protocol.Extensions.JT1078.Test/JT809.Protocol.Extensions.JT1078.Test.csproj
 - dotnet test src/JT809.Protocol.Extensions.JT1078.Test/JT809.Protocol.Extensions.JT1078.Test.csproj
after_success:
 - echo successful build!
branches:
  only:
    - master
